# **Intro to Data structures - collection of data values**
defined as group of data elements
1 variable --> containing multiple elements

oneVariable = lotsofelements!

an efficient way of storing/organising data

#**Lists In Python**

#is a collection of data values
# denoted by using [..]
#list is mutable --> changeable/modifiable contents in a list
#allows user to have duplicate elements

In [ ]:
##Creating A List

mylist = [10,20,30,40,50,60,70]
print(type(mylist))
print(mylist)

mylist1 = list([100,200,300,400])
print(type(mylist1))

##Creating an empty list

mylist2 = []

<class 'list'>
[10, 20, 30, 40, 50, 60, 70]
<class 'list'>

In [ ]:
#Lists store information as indexes
#Indexing examples
mylist = [10, 20, 30, 40, 50, 60, 70]
print(mylist[0])
#negative indexing
print(mylist[-1])
#slicing
print(mylist[1:5]) #(list[inclusive:EXCLUSIVE]),,list[]

10
70
[20, 30, 40, 50]

In [ ]:
# iteration over a list
mylist = [10, 20, 30, 40, 50, 60, 70]

for everyValue in mylist:
  print(everyValue)

10
20
30
40
50
60
70

In [ ]:
#Len function = len(list) determine how many elements in a list
mylist = [10, 20, 30, 40, 50, 60, 70]
print(len(mylist))

7

In [ ]:
#Examples of List with while loops

i = 0
while i < len(mylist):
  print(mylist[i])
  i = i + 1

10
20
30
40
50
60
70

In [ ]:
# Understanding mutable lists
mylist = [10, 20, 30, 40, 50, 60, 70]
print(mylist)

mylist[1] = 200
print(mylist)

[10, 20, 30, 40, 50, 60, 70]
[10, 200, 30, 40, 50, 60, 70]

In [ ]:
#Modifying multiple items
mylist = [10, 20, 30, 40, 50, 60, 70]
print(mylist)

mylist[:3] = [100, 200, 300]
print(mylist)

[10, 20, 30, 40, 50, 60, 70]
[100, 200, 300, 40, 50, 60, 70]

In [ ]:
# List built-in methods

mylist =  [10,20,30,40,50,60,70,80]
print(mylist)

#1. append(value) --> used to add an item at the end of a list
mylist.append(90)
print(mylist)

#2. insert (index,value) --> used to add an item at specific positions
mylist.insert(1,200)
print(mylist)

#3. pop(index) --> used to delete an item from the specified index
mylist.pop(1)
print(mylist)

#4. pop() --> if no argument specified, it will delete the last element
mylist.pop()
print(mylist)

# 5. remove(value)
mylist.remove(80)
print(mylist)

# assuming many duplicates..
list_10 = [10,20,30,40,10,10,50,60,70,10,10]
list_10.remove(10)  #it will always delete the first occurence
print(list_10)

# 6. reverse() --> used to print list in reverse order
mylist.reverse()
print(mylist)

[10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 200, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 30, 40, 50, 60, 70]
[20, 30, 40, 10, 10, 50, 60, 70, 10, 10]
[70, 60, 50, 40, 30, 20, 10]

#**Understanding Tuples**

#Tuple is a collection of data values
# denoted using ()
#tuple is immutable
#once tuple is created, you cannot update/change it

In [ ]:
#Creating a Tuple

tuple1 = (10,20,30,40,50)
print(type(tuple1))
print(tuple1)

tuple2 = tuple([1,2,3,4,5])
print(type(tuple2))

#Creating an empty tuple
tuple3 = ()
print(type(tuple3))

<class 'tuple'>
(10, 20, 30, 40, 50)
<class 'tuple'>
<class 'tuple'>

**Basic Interview Questions**

**Problem** : A single element tuple will output a integer. How to create a single element tuple without changing it to integer?

In [ ]:
myVar = 10, 20, 30, 90.21, "Yash", True

#What is the type of the variable myVar?
print(type(myVar))

#Create a tuple having a one element only?
tupl1 = (10)
print(type(tupl1))   # --> it does not register as a tuple,but int

#To create a tuple of a single element..

tupl2 = (10,)
print(type(tupl2))

<class 'tuple'>
<class 'int'>
<class 'tuple'>

**Understanding Tuple is Immutable**

#Once a tuple has been defined, you cannot change it.

In [ ]:
tuple1 = (10,20,30,40,50)
print(tuple1)

#Trying to change it. What happen?

#tuple1[1] = 200
#print(tuple1) error -- 'tuple' object does not support item assignment

#Uncomment to check out!

(10, 20, 30, 40, 50)

**Since tuple is immutable..**

In which scenario using a **tuple** is more beneficial compared to a **list?**

**vvvv** e.g : Student Final Percentage Marks **vvvvv**

**Once the marks have been recorded, none can update it, hence preferable!**

If dealing with constant values/elements, **tuple** is recommended.

If data/values/elements requires to be updated many times, **list** is recommended.

#**Understanding Tuple Inbuilt Methods**

In [2]:
tuple1 = (10,20,30,40,50,60,70,10,10,10)

# len() outputs number of elements in a tuple
print(len(tuple1)) 

# max() outputs the MAXIMUM value of a tuple
print(max(tuple1)) 

# min() outputs the MINIMUM value of a tuple
print(min(tuple1))

# tuple.count(value) counts the number of <value> in a tuple
print(tuple1.count(10))  

# index will find the 1st occurence of specified value
# tuple.index(value)
print(tuple1.index(10))
print(tuple1.index(50))
print(tuple1[7])

10
70
10
4
0
4
10

#**Understanding Sets**

#Sets --> unordered collection of data values

e.g input --> 10 20 30 40 50
    #*output --> 50 30 10 40 20*

#Denoted using **{}**
# Sets does not allow **duplicate elements**

**Creating a Set**

In [ ]:
myset = {10,20,30,40,50,10,10,20,30}
print(type(myset))
print(myset) #           Set only returns unique values IF there is duplicates.

#                     Creating sets using inbuilt functions
myset1 = set([10,20,30,40,50])
print(type(myset1))

# Creating an empty set
# if an empty set = {}, it will output a dict! (dictionary)
#myset2 = {} 
#print(type(myset2)) # output will be a dict, Uncomment to check!

#                     To create an empty set..

myset3 = set()
print(type(myset3))

<class 'set'>
{40, 10, 50, 20, 30}
<class 'set'>
<class 'set'>

# In which situation can we use sets?
All data structure is equally important.

Sets are useful when you want to find out the **UNIQUE VALUES** from a dataset/list/tuple

Example : Write a program that should print number of unique values in **list**.

In [ ]:
mylist = [10,20,30,10,30,40,50,60,30,70]
#Use for loop to iterate mylist to count unique elements.

empty_list = []

for i in mylist:              
  if i not in empty_list:
    empty_list.append(i)

print("Number of unique values are:",len(empty_list))

Number of unique values are: 7

**Step-by-step iteration of the code above**

1st iteration;;
 i == 10;; if **10 does not exist in empty_list** = **True**;;
 empty_list = [10]

 2nd iteration;;
 i == 20;; if **20 does not exist in empty_list** == **True**;;
 empty_list = [10,20]

 3rd iteration;;
 i == 30, if **30 does not exist in empty_list** == **True**;;
 empty_list = [10,20,30]

 4th iteration;;
 i == 10, if **10 does not exist in empty_list** == **False**;;
 empty_list = [10,20,30]

 5th iteration;;
 i == 30, if **30 does not exist in empty_list** == **False**;;
 empty_list = [10,20,30]

 6th iteration;;
 i == 40, if **40 does not exist in empty_list** == **True**;;
 empty_list = [10,20,30,40]

 7th iteration;;
 i == 50, if **50 does not exist in empty_list** == **True**;;
 empty_list = [10,20,30,40,50]

 8th iteration;;
 i == 60, if **60 does not exist in empty_list** == **True**;;
 empty_list = [10,20,30,40,50,60]

 9th iteration;;
 i == 30, if **30 does not exist in empty_list** == **False**;;
 empty_list = [10,20,30,40,50,60]

 10th iteration;;
 i == 70, if **70 does not exist in empty_list** == **False**;;
 empty_list = [10,20,30,40,50,60,70]

 11th iteration **for loop finished**

**However, if the dataset is a SET..**

In [ ]:
mylist = [10,20,30,10,30,40,50,60,30,70]
print("Number of unique values are:",len(set(mylist)))

Number of unique values are: 7

**Sample Interview Question : Sets**

How to create an ordered set? Is it possible?

In [ ]:
#OrderedSets
#pip = python installer package

!pip install ordered-set

Collecting ordered-set
  Downloading ordered-set-4.0.2.tar.gz (10 kB)
Building wheels for collected packages: ordered-set
  Building wheel for ordered-set (setup.py) ... done
  Created wheel for ordered-set: filename=ordered_set-4.0.2-py2.py3-none-any.whl size=8219 sha256=413ca83238bf6e01dc1940fcb055063ee1c39c443f976d1f269bf60ed069e901
  Stored in directory: /root/.cache/pip/wheels/73/2b/f6/26e9f84153c25050fe7c09e88f8e32a6be3c7034a38c418319
Successfully built ordered-set
Installing collected packages: ordered-set
Successfully installed ordered-set-4.0.2

In [ ]:
strValue = 'abracadabra'
print(set(strValue))

#To create an ordered set..

from ordered_set import OrderedSet
print(OrderedSet(strValue))

{'r', 'c', 'd', 'a', 'b'}
OrderedSet(['a', 'b', 'r', 'c', 'd'])

# **Dictionaries**

**Used to store information in key:value format**

**denoted by using {}**

normal data storage,

stInfo = [123, "Ali" , 23 , "Male" , "India"]

             0    1    2     3       4

print(stInfo[2]) ==> 23

print(stInfo[4]) ==> India

The problem is : **What if we want to store lots of data?** **It's easier to remember names than numbers.**

**Dictionaries help us by assigning keys to an element** Example..

stInfo = {123 , "Ali", 23, "Male", "India"}
           
            rno   name age gender country


**How to get country information?**

print(stInfo['country'] ==> India

**Creating a dictionary**

variable = {key:value} 

**key is always a STR value** sometimes numbers but str>numbers

**value can be anything**


# **dictionaries are immutable, keys must be unique**

**Do not repeat your keys!!**

In [ ]:
stInfo = {'rno' :123, 'name':'Ali', 'age':23}
print(type(stInfo))
print(stInfo)

print(stInfo['rno'])
print(stInfo['name'])
print(stInfo.get('age'))

<class 'dict'>
{'rno': 123, 'name': 'Ali', 'age': '23'}
123
Ali
23

**What if we have same keys in 1 dict?**

stInfo = {'rno' :123, 'name' : 'Ali', 'age' : 23, 'rno': 456}

print(stInfo) will output..

**{'rno': 456**, 'name' :'Ali', 'age': 23}

 Data for 123 will be lost

# **Understanding Iteration in Dictionaries**

normal **for** loops will always **print keys information for user**

In [ ]:
for keys in stInfo:
  print(keys)

rno
name
age

**Can we print dictionary values using for loops?**

for <temp.variable> in dictionary.values()..

In [ ]:
for val in stInfo.values():
  print(val)

123
Ali
23

**Can we print keys & values together?**

declare 2 variables, **one for keys one for values**

for **keysVariable,valuesVariable** in **dictionary.items()**:

  print(**keysVariable**,**valuesVariable**)

In [ ]:
for k,v in stInfo.items():
  print(k,v)

#For extra style points

for k,v in stInfo.items():
  print(k,'-->',v)

rno 123
name Ali
age 23
rno --> 123
name --> Ali
age --> 23