#**Pandas**

--> open-source Python Library providing high-performance **data manipulation and analysis tool**

--> tools for loading data into in-memory data objects from different file formats

--> Pandas deals with following data structures:


1.   Series
2.   DataFrame


##**Series**

--> 1D labelled array capable of holding data of **any type**


##**Dataframe**
--> 2D data structure, aligned in **tabular fashion in rows and columns**

#**Understanding Pandas**

In [2]:
import numpy as np

arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>

In [4]:
import pandas as pd
data = pd.Series(arr)
print(data)

#To print data without labels,

print(data.values)

0    10
1    20
2    30
3    40
dtype: int64
[10 20 30 40]

###**Series**

####**Storing data into series**

In [16]:
myData = pd.Series(data=[23,45,18], index=['firstPersonAge','secondPersonAge',
                                           'thirdPersonAge'])
print(myData)
print(myData['firstPersonAge'])
print(myData[0])

firstPersonAge     23
secondPersonAge    45
thirdPersonAge     18
dtype: int64
23
23

In [17]:
#For loops in pandas

for everyAge in myData:
  print(everyAge)

#But how to use for loop to print the names/index?

for age in myData.iteritems():
  print(age)

23
45
18
('firstPersonAge', 23)
('secondPersonAge', 45)
('thirdPersonAge', 18)

###**DataFrames**

In [18]:
#Traditionally dictionaries go like this..
stInfo = {'Id':[1,2,3], 'Name':['John','Smith','Alex'],
          'Course':['AI','DS','DA']}

print(stInfo)

{'Id': [1, 2, 3], 'Name': ['John', 'Smith', 'Alex'], 'Course': ['AI', 'DS', 'DA']}

Converting the data into a tabular fashion, it makes it easy to read

In [21]:
data = pd.DataFrame(stInfo)
data  

#See the difference in the formatting 
#print(data) --> Uncomment to check!

   Id   Name Course
0   1   John     AI
1   2  Smith     DS
2   3   Alex     DA

####**Using Pandas DataFrame to deal with Different File Formats**

Reading excel files

read_excel()

In [27]:
##Uploading data to pandas

# reading an excel file
# read_excel() .xlsx

data = pd.read_excel('https://trello-attachments.s3.amazonaws.com/600d1f10d700af20b1924b3c/600d1f700fcd073384905133/7c2b320aa5f10d0efa16ee38b9d53587/excelData.xlsx')
data ##It will always read Sheet no.1 by default

#What if we have multiple sheets? Another area of interest?
# Use this approach, excel file..

excel_file = pd.ExcelFile('https://trello-attachments.s3.amazonaws.com/600d1f10d700af20b1924b3c/600d1f700fcd073384905133/7c2b320aa5f10d0efa16ee38b9d53587/excelData.xlsx')
data = pd.read_excel(excel_file,'Sheet1') # Follow exactly the name of the sheet
data

data2 = pd.read_excel(excel_file, 'Sheet2')
data2

   Sno Course  Semester
0    1    MCA         5
1    2    MBA         7
2    3    BCA         2
3    4  Btech         1

Reading CSV's -- comma separated values

read_csv()

In [28]:
data = pd.read_csv('https://trello-attachments.s3.amazonaws.com/6062c6af283e86843a32b025/60d0152706cf05391bac797c/0ced7d9ccd720cb82d87e6ff95ee701c/Startups_Data.csv')
data

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

Reading TXT datasets

excel file to text

read_csv('',sep='\t') **\t = tabbed space**

In [30]:
data = pd.read_csv('https://trello-attachments.s3.amazonaws.com/600d1f10d700af20b1924b3c/600d1f700fcd073384905133/a338744c6a4359e2de64a834473f41a9/Iris.txt',sep='\t')
data

    SL   SW   PL   PW        CLASS
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

Reading json file

only to read .json

read_json()

In [31]:
data = pd.read_json('https://trello-attachments.s3.amazonaws.com/600d1f10d700af20b1924b3c/600d1f700fcd073384905133/fb8c4031dd63d317ac4b575e0481317b/sample.json')
data

                                                   widget
debug                                                  on
image   {'src': 'Images/Sun.png', 'name': 'sun1', 'hOf...
text    {'data': 'Click Here', 'size': 36, 'style': 'b...
window  {'title': 'Sample Konfabulator Widget', 'name'...

Uploading files to Colab

In [32]:
from google.colab import files
upload = files.upload()

Saving telecom_churn.csv to telecom_churn.csv

In [33]:
#Checking if dataset is uploaded

!ls #list all files on googlecolab

sample_data  telecom_churn.csv

In [35]:
data = pd.read_csv('telecom_churn.csv')
data

     state  account length  ...  customer service calls  churn
0       KS             128  ...                       1  False
1       OH             107  ...                       1  False
2       NJ             137  ...                       0  False
3       OH              84  ...                       2  False
4       OK              75  ...                       3  False
...    ...             ...  ...                     ...    ...
3328    AZ             192  ...                       2  False
3329    WV              68  ...                       3  False
3330    RI              28  ...                       2  False
3331    CT             184  ...                       2  False
3332    TN              74  ...                       0  False

[3333 rows x 21 columns]